
# SECRET_KEY=''
# MYSQL_USER = ''
# MYSQL_HOST = ''
# MYSQL_DB = ''
# MYSQL_PASSWORD = ''
# ADMIN_ROLE_ID = 0

# SQLALCHEMY_DATABASE_URI = f'mysql+mysqlconnector://:'
# SQLALCHEMY_TRACK_MODIFICATIONS = False
# SQLALCHEMY_ECHO = True


SECRET_KEY='2b0f6c24a60196f0094091f5c085d8433087e294fad6d4808ec8d881845b779a'
MYSQL_USER = ''
MYSQL_HOST = ''
MYSQL_DB = ''
MYSQL_PASSWORD = ''
ADMIN_ROLE_ID = 0

SQLALCHEMY_DATABASE_URI = f'mysql+mysqlconnector://:'
SQLALCHEMY_TRACK_MODIFICATIONS = False
SQLALCHEMY_ECHO = True